spring:
  application:
    name: category-service
  cloud:
    function:
      definition: receiveOrderInfo
    stream:
      bindings:
        receiveOrderInfo-in-0:
          destination: my-topic
          group: my-group
      kafka:
        binder:
          brokers: localhost:9092
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/category-db
    username: root
    password: 1234
  sql:
    init:
      mode: always               # Spring Boot 2.5 이상에서 사용
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
