spring:
  application:
    name: ecommerce-category-service
  cloud:
    function:
      definition: receiveCartOrderInfo
    stream:
      bindings:
        receiveCartOrderInfo-in-0:
          destination: cart-order-topic
          group: my-group
        receiveSingleOrderInfo-in-0:
          destination: single-order-topic
          group: my-group
      kafka:
        binder:
          brokers: localhost:9092
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/category-db
    username: root
    password: 1234
  sql:
    init:
      mode: always               # Spring Boot 2.5 이상에서 사용
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
